name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Testing
        uses: ./
        with:
          url: "https://mockbin.org/ips"
          number: 10
          hello: "from test action"