name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Return's the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Fetch num squared
        id: get_square
        uses: ./
        with:
          url: "https://mockbin.org/ips"
          number: 10
          hello: "from test action"